### PR TITLE
add script to download videos from youtube

### PR DESCRIPTION
**Pull request by Haaroon**
see title
requires youtube-dl
tested on macOS

### CODE REVIEW

**Comment by Willianvdv** [comment]
Hey @Haaroon, thanks for your PR! I'm not entirely sure if this the best way to download our video's, maybe we should offer the files somewhere to download so you can see them offline. How does that sound?

//cc @daeken @reedloden @martijnrusschen

**Comment by Haaroon** [comment]
Fine with me

**Comment by Haaroon** [comment]
Fine with me

**Comment by Willianvdv** [comment]
Alrighty, I'll close this PR!

**Pull request closed without merging**
