### PR TITLE
Fixed course links in 02_how_do_i_start.md

### PR DESCRIPTION
**Pull request by joelannenberg**
Course links were pointing to locations within /_resources that didn't exist.

### CODE REVIEW

**Comment by Prashles** [comment]
@joelannenberg The current links work for me in Chrome and FF. Do you see them failing elsewhere?

**Comment by joelannenberg** [comment]
They're failing for me in FF. 

It's just the three course links in the section titled "I'm new to all of this; how do I get started?"

Links

**Comment by Prashles** [comment]
Strange -- I observe this behaviour locally but not on production. Merging!

**Comment by Prashles** [comment]
Thank you @joelannenberg

**Pull request merged**
