### PR TITLE
Update 08_android_hacking_tools.md

### PR DESCRIPTION
**Pull request by bagipro**

### CODE REVIEW

**Comment by kadirselcuk** [comment]
Bu Android 10 ve üstü için geçerli midir?

**Comment by sohrab51** [comment]
Help me

**Review by sultanmehmood11 — APPROVED** [review]

**Comment by tayyabali785** [comment]
all them bakwas

**Comment by MRRTIN** [comment]
You hacking😅

**Comment by tayyabali785** [comment]
yeah afcourse

**Review by kadirselcuk — APPROVED** [review]

**Comment by duc811997** [comment]
[Account 0.txt](https://github.com/Hacker0x01/hacker101/files/5861340/Account.0.txt)

**Comment by duc811997** [comment]
> [Account 0.txt](https://github.com/Hacker0x01/hacker101/files/5861340/Account.0.txt)

**Review by duc811997 — COMMENTED** [review]
[Account 0.txt](https://github.com/Hacker0x01/hacker101/files/5861341/Account.0.txt)

**Review by kadirselcuk — APPROVED** [review]

**Review by kadirselcuk — APPROVED** [review]

**Comment by reedloden** [comment]
Doesn't seem like a good article to include in this section. If you can provide a good reason why it should be included, happy to take another look.

**Pull request closed without merging**
